# docker-compose.yml
version: '3'
services:
  flask:
    # this image will created on running command 'docker-compose up'
    image: webapp-flask
    ports:
      - "5000:5000"
    build:
      # it is telling the Docker engine to only use files
      #in the current directory to build the image
      context: .
      #to know the instructions to build the appropriate image.
      dockerfile: Dockerfile
    volumes:
      - "./:/app"